topogram:
  image: topogram/topogram
  ports:
   - "8080:8080"
  volumes:
    - "/opt/app"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo:27017/yourapp # resolves to the internal IP of the container below
   - ROOT_URL=http://localhost
   - MAIL_URL=smtp://some.mailserver.com:25 # add mailgun here
   - VIRTUAL_HOST=test.topogram.io

nginx:
  restart: always
  build: ./nginx
  volumes:
    - /www/public
  volumes_from:
    - topogram
  ports:
      - "80:80"
  links:
      - topogram:topogram


mongo:
  image: mongo:latest
  ports:
  - "27016:27017"
