nginx:
  restart: always
  build: ./nginx
  ports:
      - "80:80"
      - "443:443"
  environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
  links:
      - topogram:topogram

topogram:
  image: topogram/topogram
  ports:
   - 80
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo:27017/yourapp # resolves to the internal IP of the container below
   - ROOT_URL=http://0.0.0.0
   - MAIL_URL=smtp://some.mailserver.com:25 # add mailgun here
   - VIRTUAL_HOST=dev.topogram.io

mongo:
  image: mongo:latest
  ports:
  - "27016:27017"
